### ISSUE TITLE
Access Token returns null value

### ISSUE THREAD

**Issue by SumithSB** [nodriver-ai/flutter_azure_b2c#1]
I tried using this package for flutter web and just used the example project code itself, login was successful in web and also it displayed userinfo error handling in source code of the package .
But when i request for access token it gives me null value.

**Comment by chipscal** [comment]
Hi! in the example in order to acquire the access token you should first press on the userinfo button to retrieve the subject of the user. This subject is a string that is used to discriminate among different logged users. 

    """ it displayed userinfo error handling in source code of the package """
Sorry, I didn't understood this sentence. Do you have any error? Could you please copy/paste directly the error?

**Comment by SumithSB** [comment]
Hi there,
Thank you for your reply, I have actually figured out the problem actually
my token was being sent as idToken key value pair and also the expireson
timestamp parsing was throwing some error which I was able to solve after
some tweaking in the package source code.

But thank you very much , this package really saved me I was really stuck
with azure b2c integration from past 2 weeks.

**Comment by chipscal** [comment]
You're welcome! Yes you should disable every implicit grand and flow flag in the authentication panel...

   """ expireson timestamp parsing """
I remember I had some issues with this in the past and for us now is working. Whenever you have time could you please better describe the issue you had and post your solution? Thank you!

**Comment by SumithSB** [comment]
Sure, will do that.
Thank you

**Comment by chipscal** [comment]
v0.0.5 definitely solved the problem.
