### ISSUE TITLE
iOS  MSALErrorDomain error -50000.

### ISSUE THREAD

**Issue by tariq-alskran** [nodriver-ai/flutter_azure_b2c#10]
Unexpected error: The operation couldn’t be completed. (MSALErrorDomain error -50000.)

**Comment by tariq-alskran** [comment]
Solved
There were some problems with my azure b2c settings

**Comment by alex-dokienko** [comment]
hi @tariq-alskran , 
May I ask how you solved that? What was missed?

**Comment by tariq-alskran** [comment]
It was confiugration file issue make sure to add correct  file to your android project

**Comment by alex-dokienko** [comment]
yeah, android is working fine, iOS implementation is what is making me crazy.
currently I managed to load configuration file but getting issues on authority
[1]	(null)	"MSALInternalErrorCodeKey" : Int64(-42008)	
[0]	(null)	"MSALErrorDescriptionKey" : "Authority validation is not supported for this type of authority"	
that's when I use normal format 
https://{tenant}.b2clogin.com/{tenant}.onmicrosoft.com/{policy}

apparently it expects something like 
https://login.microsoftonline.com/tfp/{tenant}.onmicrosoft.com/{policy}
from this [link](https://learn.microsoft.com/en-us/azure/active-directory/develop/config-authority?WT.mc_id=Portal-Microsoft_AAD_RegisteredApps#b2c)
but then I get 
[1]	(null)	"MSALInternalErrorCodeKey" : Int64(-42007)	
with some 403 permission description
