### ISSUE TITLE
App crash in release

### ISSUE THREAD

**Issue by BusyBaptiste** [nodriver-ai/flutter_azure_b2c#16]
Hello,

I have integrated the flutter_azure_b2c package in my application. Everything works perfectly in DEBUG, on emulator or on a real phone. When I build in DEBUG and install the APK it works too, but if I build in RELEASE the application crashes. I think this is because in RELEASE the auth_config file is not found. How is this possible and how to fix it?

Thanks

**Comment by jchirinosodio** [comment]
Hi there, same issue here

**Comment by jchirinosodio** [comment]
> Hi there, same issue here



> Hello,
> 
> I have integrated the flutter_azure_b2c package in my application. Everything works perfectly in DEBUG, on emulator or on a real phone. When I build in DEBUG and install the APK it works too, but if I build in RELEASE the application crashes. I think this is because in RELEASE the auth_config file is not found. How is this possible and how to fix it?
> 
> Thanks

Have you found any solution? I am expericing the same issue!

**Comment by euphoria3k** [comment]
I found the fix for this issue! You have to set minifyEnabled to false and shrinkResources to false in the buildTypes -> release section of your app's build.gradle.

I hope this helps!

**Comment by emaborsa** [comment]
This fixed it:

```
 buildTypes {
        release {
            ...
            minifyEnabled false
            shrinkResources false
        }
    }
```

**Comment by markopex** [comment]
Fix is working but I think it's maybe wrong way to solve it, why not try to add missing stuffs in the ProGuard file?
`-keep class com.microsoft.** {
  *;
}
`
This will probably solve the issue without losing optimisations. 
Please check https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/513
