### ISSUE TITLE
B2COperationResult.result ClientError

### ISSUE THREAD

**Issue by emaborsa** [nodriver-ai/flutter_azure_b2c#17]
Hi all,
Flutter 3.7.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 32fb2f948e (22 hours ago) • 2023-02-08 07:30:10 -0800
Engine • revision f40b73f8a4
Tools • Dart 2.19.2 • DevTools 2.20.1

using flutter_azure_b2c: ^0.0.9

From the following callback, the result is CLIENT_ERROR:
```
AzureB2C.registerCallback(B2COperationSource.INIT, (result) async {
  if (result.reason == B2COperationState.SUCCESS) {
    _configuration = await AzureB2C.getConfiguration();
  }
});
```

What I am missing?

**Comment by chipscal** [comment]
Maybe everything.. ;D Are you building for Web, android or ios? Have you followed the readme? Created the configuration file? Configured your b2c directory?

**Comment by emaborsa** [comment]
Sorry, forgot to mention, android, yes followed the readme and created the configuration file.
After hours of struggling, I have been able to get result success.

**Comment by shubhshah01** [comment]
Hi @emaborsa,
Can you tell what did you do to solve this ?

**Comment by emaborsa** [comment]
> Hi @emaborsa, Can you tell what did you do to solve this ?

Sorry did not see your post, and honestly, I don't remember :/
