### ISSUE TITLE
iOS implementation 

### ISSUE THREAD

**Issue by durmisi** [nodriver-ai/flutter_azure_b2c#2]
I would like you to ask you when to expect the iOS implementation?
Thank you for the good work, the package is working on my web/android apps.

**Comment by chipscal** [comment]
Hi durmisi,

I think not before next year because for now we do not have urgency to support iOS...

**Comment by punitganshani** [comment]
any update on timelines?

**Comment by chipscal** [comment]
We released today v0.0.8 with iOs support!
