### ISSUE TITLE
Getting 'CLIENT_ERROR' on web version

### ISSUE THREAD

**Issue by karimi1064** [nodriver-ai/flutter_azure_b2c#4]
I prepare a configuration file according the template in the path of "web/assets/auth_config.json" and run the example, but get
`Callback data: {"tag":"885e5899-a955-41a9-a37c-94ecd7fc7158","source":"init","reason":"CLIENT_ERROR"}`

Please guide me.

**Comment by karimi1064** [comment]
Although after almost 20 times refresh, sometimes I get '`SUCCESS`'!!!

**Comment by chipscal** [comment]
Inactivity.

**Comment by shubhshah01** [comment]
any fix for this ?
